# Generated by Django 4.1.5 on 2023-03-06 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adresse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.CharField(blank=True, max_length=20, unique=True)),
                ('email', models.CharField(max_length=250, unique=True)),
                ('quartier', models.CharField(max_length=150)),
                ('ville', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Banque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('montant', models.CharField(max_length=200)),
                ('validation', models.FloatField(blank=True, max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Personne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('naissance', models.DateTimeField(verbose_name='date de naisssance')),
                ('genre', models.CharField(choices=[('M', 'masculin'), ('F', 'feminin'), ('Autre', 'autre')], max_length=32)),
                ('status', models.CharField(choices=[('Ancien', 'ancien'), ('Nouveau', 'nouveau')], max_length=32)),
                ('photo', models.ImageField(blank=True, upload_to='static/photo')),
                ('adresse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employéapp.adresse', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('personne_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='employéapp.personne')),
                ('matricule', models.CharField(max_length=20, unique=True)),
                ('service', models.CharField(max_length=100)),
                ('contrat', models.CharField(choices=[('ST', 'stagiaire'), ('CDD', 'Contrat à durée déterminé'), ('CDI', 'Contrat à durée indéterminé')], max_length=32)),
            ],
            bases=('employéapp.personne',),
        ),
        migrations.CreateModel(
            name='Recu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='date de naisssance')),
                ('montant', models.CharField(max_length=200)),
                ('reste', models.CharField(max_length=200)),
                ('numero', models.CharField(max_length=120)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employéapp.employe')),
            ],
        ),
    ]
