# Generated by Django 4.1.4 on 2023-03-16 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employéapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recu',
            name='date',
            field=models.DateTimeField(verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='recu',
            name='employe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employéapp.employe', unique=True),
        ),
    ]
